-- File generated by the BNF Converter (bnfc 2.9.4.1).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for LBNF.

module LBNF.LBNF.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified LBNF.LBNF.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print LBNF.LBNF.Abs.Ident where
  prt _ (LBNF.LBNF.Abs.Ident i) = doc $ showString i
instance Print LBNF.LBNF.Abs.Grammar where
  prt i = \case
    LBNF.LBNF.Abs.MkGrammar defs -> prPrec i 0 (concatD [prt 0 defs])

instance Print [LBNF.LBNF.Abs.Def] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print [LBNF.LBNF.Abs.Item] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print LBNF.LBNF.Abs.Def where
  prt i = \case
    LBNF.LBNF.Abs.Rule label cat items -> prPrec i 0 (concatD [prt 0 label, doc (showString "."), prt 0 cat, doc (showString "::="), prt 0 items])
    LBNF.LBNF.Abs.Comment str -> prPrec i 0 (concatD [doc (showString "comment"), printString str])
    LBNF.LBNF.Abs.Comments str1 str2 -> prPrec i 0 (concatD [doc (showString "comment"), printString str1, printString str2])
    LBNF.LBNF.Abs.Internal label cat items -> prPrec i 0 (concatD [doc (showString "internal"), prt 0 label, doc (showString "."), prt 0 cat, doc (showString "::="), prt 0 items])
    LBNF.LBNF.Abs.Token id_ reg -> prPrec i 0 (concatD [doc (showString "token"), prt 0 id_, prt 0 reg])
    LBNF.LBNF.Abs.PosToken id_ reg -> prPrec i 0 (concatD [doc (showString "position"), doc (showString "token"), prt 0 id_, prt 0 reg])
    LBNF.LBNF.Abs.Entryp ids -> prPrec i 0 (concatD [doc (showString "entrypoints"), prt 0 ids])
    LBNF.LBNF.Abs.Separator minimumsize cat str -> prPrec i 0 (concatD [doc (showString "separator"), prt 0 minimumsize, prt 0 cat, printString str])
    LBNF.LBNF.Abs.Terminator minimumsize cat str -> prPrec i 0 (concatD [doc (showString "terminator"), prt 0 minimumsize, prt 0 cat, printString str])
    LBNF.LBNF.Abs.Coercions id_ n -> prPrec i 0 (concatD [doc (showString "coercions"), prt 0 id_, prt 0 n])
    LBNF.LBNF.Abs.Rules id_ rhss -> prPrec i 0 (concatD [doc (showString "rules"), prt 0 id_, doc (showString "::="), prt 0 rhss])
    LBNF.LBNF.Abs.Variable variabletype cat -> prPrec i 0 (concatD [doc (showString "variable"), prt 0 variabletype, prt 0 cat])
    LBNF.LBNF.Abs.Layout strs -> prPrec i 0 (concatD [doc (showString "layout"), prt 0 strs])
    LBNF.LBNF.Abs.LayoutStop strs -> prPrec i 0 (concatD [doc (showString "layout"), doc (showString "stop"), prt 0 strs])
    LBNF.LBNF.Abs.LayoutTop -> prPrec i 0 (concatD [doc (showString "layout"), doc (showString "toplevel")])

instance Print LBNF.LBNF.Abs.Item where
  prt i = \case
    LBNF.LBNF.Abs.Terminal str -> prPrec i 0 (concatD [printString str])
    LBNF.LBNF.Abs.NTerminal cat -> prPrec i 0 (concatD [prt 0 cat])

instance Print LBNF.LBNF.Abs.Cat where
  prt i = \case
    LBNF.LBNF.Abs.ListCat cat -> prPrec i 0 (concatD [doc (showString "["), prt 0 cat, doc (showString "]")])
    LBNF.LBNF.Abs.IdCat id_ -> prPrec i 0 (concatD [prt 0 id_])

instance Print LBNF.LBNF.Abs.Label where
  prt i = \case
    LBNF.LBNF.Abs.LabNoP labelid -> prPrec i 0 (concatD [prt 0 labelid])
    LBNF.LBNF.Abs.LabP labelid profitems -> prPrec i 0 (concatD [prt 0 labelid, prt 0 profitems])
    LBNF.LBNF.Abs.LabPF labelid1 labelid2 profitems -> prPrec i 0 (concatD [prt 0 labelid1, prt 0 labelid2, prt 0 profitems])
    LBNF.LBNF.Abs.LabF labelid1 labelid2 -> prPrec i 0 (concatD [prt 0 labelid1, prt 0 labelid2])

instance Print LBNF.LBNF.Abs.LabelId where
  prt i = \case
    LBNF.LBNF.Abs.Id id_ -> prPrec i 0 (concatD [prt 0 id_])
    LBNF.LBNF.Abs.Wild -> prPrec i 0 (concatD [doc (showString "_")])
    LBNF.LBNF.Abs.ListE -> prPrec i 0 (concatD [doc (showString "["), doc (showString "]")])
    LBNF.LBNF.Abs.ListCons -> prPrec i 0 (concatD [doc (showString "("), doc (showString ":"), doc (showString ")")])
    LBNF.LBNF.Abs.ListOne -> prPrec i 0 (concatD [doc (showString "("), doc (showString ":"), doc (showString "["), doc (showString "]"), doc (showString ")")])

instance Print LBNF.LBNF.Abs.ProfItem where
  prt i = \case
    LBNF.LBNF.Abs.ProfIt intlists ns -> prPrec i 0 (concatD [doc (showString "("), doc (showString "["), prt 0 intlists, doc (showString "]"), doc (showString ","), doc (showString "["), prt 0 ns, doc (showString "]"), doc (showString ")")])

instance Print LBNF.LBNF.Abs.IntList where
  prt i = \case
    LBNF.LBNF.Abs.Ints ns -> prPrec i 0 (concatD [doc (showString "["), prt 0 ns, doc (showString "]")])

instance Print [Integer] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [LBNF.LBNF.Abs.IntList] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [LBNF.LBNF.Abs.ProfItem] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print LBNF.LBNF.Abs.VariableType where
  prt i = \case
    LBNF.LBNF.Abs.VarScope -> prPrec i 0 (concatD [doc (showString "scope")])
    LBNF.LBNF.Abs.VarName -> prPrec i 0 (concatD [doc (showString "name")])
    LBNF.LBNF.Abs.VarBinder -> prPrec i 0 (concatD [doc (showString "binder")])

instance Print [String] where
  prt _ [] = concatD []
  prt _ [x] = concatD [printString x]
  prt _ (x:xs) = concatD [printString x, doc (showString ","), prt 0 xs]

instance Print [LBNF.LBNF.Abs.RHS] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString "|"), prt 0 xs]

instance Print LBNF.LBNF.Abs.RHS where
  prt i = \case
    LBNF.LBNF.Abs.MkRHS items -> prPrec i 0 (concatD [prt 0 items])

instance Print LBNF.LBNF.Abs.MinimumSize where
  prt i = \case
    LBNF.LBNF.Abs.MNonempty -> prPrec i 0 (concatD [doc (showString "nonempty")])
    LBNF.LBNF.Abs.MEmpty -> prPrec i 0 (concatD [])

instance Print LBNF.LBNF.Abs.Reg where
  prt i = \case
    LBNF.LBNF.Abs.RSeq reg1 reg2 -> prPrec i 2 (concatD [prt 2 reg1, prt 3 reg2])
    LBNF.LBNF.Abs.RAlt reg1 reg2 -> prPrec i 1 (concatD [prt 1 reg1, doc (showString "|"), prt 2 reg2])
    LBNF.LBNF.Abs.RMinus reg1 reg2 -> prPrec i 1 (concatD [prt 2 reg1, doc (showString "-"), prt 2 reg2])
    LBNF.LBNF.Abs.RStar reg -> prPrec i 3 (concatD [prt 3 reg, doc (showString "*")])
    LBNF.LBNF.Abs.RPlus reg -> prPrec i 3 (concatD [prt 3 reg, doc (showString "+")])
    LBNF.LBNF.Abs.ROpt reg -> prPrec i 3 (concatD [prt 3 reg, doc (showString "?")])
    LBNF.LBNF.Abs.REps -> prPrec i 3 (concatD [doc (showString "eps")])
    LBNF.LBNF.Abs.RChar c -> prPrec i 3 (concatD [prt 0 c])
    LBNF.LBNF.Abs.RAlts str -> prPrec i 3 (concatD [doc (showString "["), printString str, doc (showString "]")])
    LBNF.LBNF.Abs.RSeqs str -> prPrec i 3 (concatD [doc (showString "{"), printString str, doc (showString "}")])
    LBNF.LBNF.Abs.RDigit -> prPrec i 3 (concatD [doc (showString "digit")])
    LBNF.LBNF.Abs.RLetter -> prPrec i 3 (concatD [doc (showString "letter")])
    LBNF.LBNF.Abs.RUpper -> prPrec i 3 (concatD [doc (showString "upper")])
    LBNF.LBNF.Abs.RLower -> prPrec i 3 (concatD [doc (showString "lower")])
    LBNF.LBNF.Abs.RAny -> prPrec i 3 (concatD [doc (showString "char")])

instance Print [LBNF.LBNF.Abs.Ident] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]
