-- File generated by the BNF Converter (bnfc 2.9.4.1).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module LCalc.LambdaCalculus.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified LCalc.LambdaCalculus.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: LCalc.LambdaCalculus.Abs.Ident -> Result
transIdent x = case x of
  LCalc.LambdaCalculus.Abs.Ident string -> failure x

transProgram :: LCalc.LambdaCalculus.Abs.Program -> Result
transProgram x = case x of
  LCalc.LambdaCalculus.Abs.AProgram terms -> failure x

transTerm :: LCalc.LambdaCalculus.Abs.Term -> Result
transTerm x = case x of
  LCalc.LambdaCalculus.Abs.Var variable -> failure x
  LCalc.LambdaCalculus.Abs.IntConst integer -> failure x
  LCalc.LambdaCalculus.Abs.DoubleConst double -> failure x
  LCalc.LambdaCalculus.Abs.Binder variable term -> failure x
  LCalc.LambdaCalculus.Abs.LetBinder variable term1 term2 -> failure x
  LCalc.LambdaCalculus.Abs.Application term1 term2 -> failure x
  LCalc.LambdaCalculus.Abs.Plus term1 term2 -> failure x
  LCalc.LambdaCalculus.Abs.Minus term1 term2 -> failure x

transVariable :: LCalc.LambdaCalculus.Abs.Variable -> Result
transVariable x = case x of
  LCalc.LambdaCalculus.Abs.Identifier ident -> failure x
