-- File generated by the BNF Converter (bnfc 2.9.4.1).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language DeBruijnGrammar.

module DBruijnCalc.DeBruijnGrammar.Abs where

import Prelude (Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Program = AProgram [Term]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Term
    = Var VarIdent
    | Application Term Term
    | Lam ScopedTerm
    | Let Term ScopedTerm
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ScopedTerm = ScopedTerm Term
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data VarIdent = VarIdent Ident | DBBound Integer
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

