-- File generated by the BNF Converter (bnfc 2.9.4.1).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module DBruijnCalc.DeBruijnGrammar.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified DBruijnCalc.DeBruijnGrammar.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: DBruijnCalc.DeBruijnGrammar.Abs.Ident -> Result
transIdent x = case x of
  DBruijnCalc.DeBruijnGrammar.Abs.Ident string -> failure x

transProgram :: DBruijnCalc.DeBruijnGrammar.Abs.Program -> Result
transProgram x = case x of
  DBruijnCalc.DeBruijnGrammar.Abs.AProgram terms -> failure x

transTerm :: DBruijnCalc.DeBruijnGrammar.Abs.Term -> Result
transTerm x = case x of
  DBruijnCalc.DeBruijnGrammar.Abs.Var variable -> failure x
  DBruijnCalc.DeBruijnGrammar.Abs.IntConst integer -> failure x
  DBruijnCalc.DeBruijnGrammar.Abs.DoubleConst double -> failure x
  DBruijnCalc.DeBruijnGrammar.Abs.Binder term -> failure x
  DBruijnCalc.DeBruijnGrammar.Abs.LetBinder term1 term2 -> failure x
  DBruijnCalc.DeBruijnGrammar.Abs.Application term1 term2 -> failure x
  DBruijnCalc.DeBruijnGrammar.Abs.Plus term1 term2 -> failure x
  DBruijnCalc.DeBruijnGrammar.Abs.Minus term1 term2 -> failure x

transVariable :: DBruijnCalc.DeBruijnGrammar.Abs.Variable -> Result
transVariable x = case x of
  DBruijnCalc.DeBruijnGrammar.Abs.Identifier ident -> failure x
  DBruijnCalc.DeBruijnGrammar.Abs.Bound integer -> failure x
