-- File generated by the BNF Converter (bnfc 2.9.4.1).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module DBruijnCalc.DeBruijnGrammar.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified DBruijnCalc.DeBruijnGrammar.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: DBruijnCalc.DeBruijnGrammar.Abs.Ident -> Result
transIdent x = case x of
  DBruijnCalc.DeBruijnGrammar.Abs.Ident string -> failure x

transProgram :: DBruijnCalc.DeBruijnGrammar.Abs.Program -> Result
transProgram x = case x of
  DBruijnCalc.DeBruijnGrammar.Abs.AProgram terms -> failure x

transTerm :: DBruijnCalc.DeBruijnGrammar.Abs.Term -> Result
transTerm x = case x of
  DBruijnCalc.DeBruijnGrammar.Abs.Var varident -> failure x
  DBruijnCalc.DeBruijnGrammar.Abs.Application term1 term2 -> failure x
  DBruijnCalc.DeBruijnGrammar.Abs.Lam scopedterm -> failure x
  DBruijnCalc.DeBruijnGrammar.Abs.Let term scopedterm -> failure x

transScopedTerm :: DBruijnCalc.DeBruijnGrammar.Abs.ScopedTerm -> Result
transScopedTerm x = case x of
  DBruijnCalc.DeBruijnGrammar.Abs.ScopedTerm term -> failure x

transVarIdent :: DBruijnCalc.DeBruijnGrammar.Abs.VarIdent -> Result
transVarIdent x = case x of
  DBruijnCalc.DeBruijnGrammar.Abs.VarIdent ident -> failure x
  DBruijnCalc.DeBruijnGrammar.Abs.DBBound integer -> failure x
